// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ts_num_individuals_ptr2
int ts_num_individuals_ptr2(const SEXP ts);
RcppExport SEXP _RcppTskitTestLinking_ts_num_individuals_ptr2(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_individuals_ptr2(ts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppTskitTestLinking_ts_num_individuals_ptr2", (DL_FUNC) &_RcppTskitTestLinking_ts_num_individuals_ptr2, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppTskitTestLinking(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
