# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Get number of individuals in tree sequence
#' @param ts an external pointer to a \code{tsk_treeseq_t} object.
#' @return integer number of individuals.
#' @examples
#' ts_file <- system.file("examples", "test.trees", package = "RcppTskit")
#' ts <- RcppTskit::ts_load(ts_file)
#' ts$num_individuals()
#' ts_num_individuals_ptr2(ts$pointer)
#' @export
ts_num_individuals_ptr2 <- function(ts) {
    .Call(`_RcppTskitTestLinking_ts_num_individuals_ptr2`, ts)
}

